//v165 Copyright (c) 2008-2020 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
"undefined"==typeof Tynt.TIL&&"undefined"==typeof Tynt.TCL&&"undefined"==typeof Tynt.TICFL&&function(){var e=window,g=document,h={distro:"TC",id:"TC-"+(new Date).getTime()};Tynt.TCL=function(){function Y(a,b,c){f.on(a,b,c)}function L(a){var b=L.options;a=b.parser[b.strictMode?"strict":"loose"].exec(a);for(var c={},d=14;d--;)c[b.key[d]]=a[d]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(a,d,e){d&&(c[b.q.name][d]=e)});return c}if(document.body){Date.now||(Date.now=function(){return(new Date).getTime()});
var f={_maxRef:600,_idMacro:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",init:function(){this._icUrl=h.protocol+(Tynt.e||"")+"ic.tynt.com";this._debUrl=h.protocol+(Tynt.e||"")+"de.tynt.com/deb/v2";this._sicUrl=h.protocol+(Tynt.e||"")+"cdn-sic.33across.com/1/javascripts/sic.js";this._apUrl=h.protocol+(Tynt.e||"")+"cdn-ap.33across.com/javascripts/ap.js"},newEle:function(a,b,c,d){d=d||window;a=d.document.createElement(a);b&&this.extend(a,b);c&&this.extend(a.style,c);return a},injectScript:function(a,
b,c){b=b||window;a=this.newEle("script",{async:"async",referrerPolicy:"unsafe-url",type:"text/javascript",src:a},null,b);this.insertEle(a,c||b.document.getElementsByTagName("script")[0])},injectSicScript:function(a){this.injectScript(this._sicUrl,window,a)},injectApolloScript:function(){this.injectScript(this._apUrl)},injectSicIframe:function(a,b,c){var d={width:a.width+"px",height:a.height+"px",border:"0 none",margin:"0"};c&&this.extend(d,c);c=this.newEle("iframe",{referrerPolicy:"unsafe-url",src:"about:blank",
frameBorder:"0",frameSpacing:"0",scrolling:"no"},d);this.insertEle(c,b);a.iframeId=this.eleId(c);a.sicWindow=c.contentWindow;a=c.contentWindow.document;a.open();a.write('<!DOCTYPE html><html><head><style type="text/css">*{margin:0;padding:0;}</style></head><body><script type="text/javascript">window.Tynt = window.parent.Tynt;\x3c/script><script type="text/javascript" src="'+this._sicUrl+'">\x3c/script></body></html>');a.close()},insertEle:function(a,b){b?"script"==b.tagName.toLowerCase()?b.parentNode.insertBefore(a,
b):b.appendChild(a):document.body.appendChild(a)},eleId:function(a){var b=a.id;b||(b="x33x"+Date.now(),a.id=b);return b},_imgs:[],injectPixel:function(a,b,c){var d;try{d=g.createElement("img")}catch(l){d=document.createElement("img")}d&&(this._imgs.push(d),b&&(d.onload=b),c&&(d.onerror=c),d.referrerPolicy="unsafe-url",d.src=a)},docUrl:function(){var a=this.getLink("canonical");a||(a=this.getMeta("property","og:url","name","original-source"));if(a){if(0!=a.indexOf("http")){var b=h.protocol+e.location.host+
e.location.pathname,c=g.getElementsByTagName("base")[0];c&&(c=c.getAttribute("href"))&&(b=c);"/"==a.charAt(0)?(c=b.indexOf("/",9),-1<c&&(b=b.slice(0,c))):(c=b.lastIndexOf("/"),b=9<c?b.slice(0,c+1):b+"/");a=b+a}return a}return""},getMeta:function(a,b,c,d){var l,e=null,f=null,k=g.getElementsByTagName("meta");for(l=0;l<k.length;++l)e||k[l].getAttribute(a)!==b?c&&!f&&k[l].getAttribute(c)===d&&(f=k[l].getAttribute("content")||null):e=k[l].getAttribute("content")||null;return e||f},getLink:function(a,b){var c,
d,l=g.getElementsByTagName("link");for(c=0;c<l.length;++c)if(d=l[c].getAttribute("rel"),l[c].getAttribute("href")&&d&&(!b&&0<=d.indexOf(a)||b&&d==a))return l[c].href;return null},extend:function(a,b){var c,d;for(c=1;c<arguments.length;++c)for(d in arguments[c])arguments[c].hasOwnProperty(d)&&(a[d]=arguments[c][d]);return a},isArray:function(a){return"undefined"!=typeof a&&"[object Array]"===Object.prototype.toString.call(a)},inArray:function(a,b){return 0<=this.indexOf(a,b)},toArray:function(a,b){return Array.prototype.slice.call(a,
b||0)},indexOf:function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1},unique:function(a){var b,c={},d=[];for(b=0;b<a.length;++b)c[a[b]]||(c[a[b]]=!0,d.push(a[b]));return d},iframeType:function(){var a=this.iframeEle(),b=M,c=", iso:"+this.isolated();if(a)a.id&&0<=a.id.search(/google_ads?_i?frame/)?(b=6,f.clog("In same-origin iframe from DFP"+c)):(b=N,f.clog("In same-origin iframe"+c));else try{window!=window.top?"undefined"!=typeof window.$sf?(b=O,
f.clog("In SafeFrame")):(b=A,f.clog("In cross-origin iframe")):f.clog("In top window")}catch(d){b=A,f.clog("iframeType: "+d.message)}return b},iframeEle:function(a){var b=null;a=a||window;try{b=a.frameElement}catch(c){}return b},iframeTop:function(){var a=window,b=null;try{for(;a!=window.top;)b=a,a=a.parent}catch(c){return null}return b?this.iframeEle(b):null},getTopWin:function(){var a=window;try{for(;a.parent!==a&&a.parent.document;)a=a.parent}catch(b){}return a},isolated:function(){var a=!0;try{"function"==
typeof window.top.open&&(a=!1)}catch(b){}return a},tyntIds:function(){return this.unique(Tynt).join("~")},getPubId:function(){for(var a=null,b=0;b<Tynt.length;++b)if("string"==typeof Tynt[b]&&22==Tynt[b].length&&0>Tynt[b].indexOf("!")){a=Tynt[b];break}return a},countIds:function(a){var b,c=0;for(b=0;b<Tynt.length;++b)Tynt[b]===a&&++c;return c},_log:function(a){"undefined"==typeof Tynt.debug&&0<e.location.search.indexOf("__tcdebugmode=1")&&e.console&&e.console.log&&(Tynt.debug=!0);if(!0===Tynt.debug||
1===Tynt.debug)a.unshift("[TC]"),e.console.log.apply(e.console,a)},log:function(){h.inXOIframe()?this.clog.apply(this,arguments):this._log(this.toArray(arguments))},clog:function(){var a=this.toArray(arguments);a.unshift(h.id);this._log(a)},callIc:function(){var a,b,c,d,l,z,n,k;if(!e._33Across.state.icDone){e._33Across.state.icDone=Z;b=this.getCookie(g.cookie,"tracertraffic");a=e.location.hash;a=/tynt=/.test(a)?a.match(/tynt=?([^?&$#]*)/)[1]:!1;d=c=this._icUrl+"/b/p?id="+this.tyntIds()+(b?"&et="+
b:"")+(a?"&a="+a:"")+("string"==typeof Tynt.b?"&b="+Tynt.b:"")+"&lm="+h.type+"&ts="+Date.now()+"&dn="+h.distro+"&iso="+(this.isolated()?"1":"0")+(null==G.uspString?"":"&us_privacy="+G.uspString);(a=this.getMeta("property","og:image:url","property","og:image"))&&(d+="&img="+encodeURIComponent(this.trunc(a,250)));l=d;(a=this.getMeta("property","og:title"))&&a!=g.title&&(l+="&ct="+encodeURIComponent(this.trunc(a,200)));z=l;g.referrer&&(a=this.trunc(g.referrer,this._maxRef),z+="&r="+encodeURIComponent(a));
n=z;if(a=g.title||e.location.hostname)a=this.trim(this.trunc(a,200)),n+="&t="+encodeURIComponent(a);k=n;if(a=this.docUrl())a=this.trunc(a,400),k+="&cu="+encodeURIComponent(a);b=k;if(a=this.getLink("amphtml",!0))a=this.trunc(a,250),b+="&ah="+encodeURIComponent(a);f.callIc.rsp=function(){e._33Across.state.icDone=H};f.clog("Calling IC");this.injectPixel(b,f.callIc.rsp,function(){f.injectPixel(k,f.callIc.rsp,function(){f.injectPixel(n,f.callIc.rsp,function(){f.injectPixel(z,f.callIc.rsp,function(){f.injectPixel(l,
f.callIc.rsp,function(){f.injectPixel(d,f.callIc.rsp,function(){f.injectPixel(c,f.callIc.rsp)})})})})})})}},callDeb:function(a,b,c){function d(a,b){f.clog("Calling DEB "+b+(a?"":" on IC timeout"));var c=encodeURIComponent(f.trunc(g.referrer,f._maxRef));f.injectScript(f._debUrl+"?id="+f.tyntIds()+"&dn="+h.distro+"&cc="+b+"&r="+c,e)}"undefined"==typeof a&&(a=1);e._33Across.state.deDone>=a||(++e._33Across.state.deDone,1!==e._33Across.state.deDone&&!0!==c||this.when(function(){return e._33Across.state.icDone==
H},d,{timeout:300,timeoutCallback:d,callbackData:e._33Across.state.deDone},this),b&&0<b.length&&setTimeout(function(){f.callDeb(a,b,!0)},b.shift()))},callDebX:function(a,b){function c(a,c){f[b?"log":"clog"]("Calling DEBx "+c+(a?"":" on IC timeout"));var z=encodeURIComponent(f.trunc(g.referrer,f._maxRef)),n=I.consentString?"&gdpr_consent="+I.consentString:"";f.injectScript(f._debUrl+"?m=xch&id="+f.tyntIds()+"&dn="+h.distro+"&cc="+c+"&r="+z+n,e)}a||(a=10);e._33Across.state.dxDone>=a||(++e._33Across.state.dxDone,
this.when(function(){return e._33Across.state.icDone==H},c,{timeout:300,timeoutCallback:c,callbackData:e._33Across.state.dxDone},this))},jsonDecode:function(a){if("function"!=typeof Array.prototype.toJSON)return JSON.stringify(a);var b=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=b;return a},getCookie:function(a,b){for(var c=b+"=",d=a.split(";"),l=0;l<d.length;l++){for(var e=d[l];" "==e.charAt(0);)e=e.substring(1,e.length);if(0==e.indexOf(c))return e.substring(c.length,
e.length)}return null},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},trunc:function(a,b){var c,d;if(!a||a.length<=b)return a;c=a.substring(0,b);for(d=1;3>=d;++d)if("%"==c.charAt(c.length-d))return c.substring(0,c.length-d);return c},when:function(a,b,c,d){var l,f,n,k=null,P=null,g=a();c=c||{};l=c.interval||50;f=c.timeout;n=c.timeoutCallback||function(){};if(g)return b.call(d,g,c.callbackData),!0;k=e.setInterval(function(){if(g=a())e.clearInterval(k),e.clearTimeout(P),b.call(d,g,c.callbackData)},
l);f&&(P=e.setTimeout(function(){e.clearInterval(k);n.call(d,g,c.callbackData)},f));return!1},prob:function(a){a=parseFloat(a)||0;return Math.random()<a},on:function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,d||!1):a.attachEvent&&a.attachEvent("on"+b,c)},off:function(a,b,c,d){a.removeEventListener?a.removeEventListener(b,c,d||!1):a.detachEvent&&a.detachEvent("on"+b,c)}},I={consentString:null,init:function(){var a=this,b=function(){for(var a=window,b;!b;){try{a.frames.__cmpLocator&&(b=a)}catch(c){}if(a===
window.top)break;a=a.parent}var d={};e.__cmp=function(a,c,e){if(b){var l=Math.random()+"";a={__cmpCall:{command:a,parameter:c,callId:l}};d[l]=e;b.postMessage(a,"*")}else e({msg:"CMP not found"},!1)};f.on(window,"message",function(a){var b=a.data;if("string"===typeof a.data)try{b=JSON.parse(a.data)}catch(c){}b.__cmpReturn&&(a=b.__cmpReturn,d[a.callId](a.returnValue,a.success),delete d[a.callId])},!1)},c=function(){e.__cmp("getConsentData",null,function(b,c){c&&(a.consentString=b.consentData)})};e.__cmp||
b();try{c()}catch(d){b(),c()}Tynt.getConsentString=function(){return a.consentString}}},G={uspString:null,init:function(){var a=this,b=function(){for(var a=window,b;!b;){try{a.frames.__uspapiLocator&&(b=a)}catch(c){}if(a===window.top)break;a=a.parent}var d={};e.__uspapi=function(a,c,e){if(b){var f="usp-"+Math.random();a={__uspapiCall:{command:a,callId:f,version:c}};d[f]=e;b.postMessage(a,"*")}else e({msg:"__uspapi not found"},!1)};f.on(window,"message",function(a){var b=a.data;if("string"===typeof a.data)try{b=
JSON.parse(a.data)}catch(c){}b.__uspapiReturn&&(a=b.__uspapiReturn,d[a.callId](a.returnValue,a.success),delete d[a.callId])},!1)},c=function(){e.__uspapi("getUSPData",1,function(b,c){c&&(a.uspString=b.uspString)})};e.__uspapi||b();try{c()}catch(d){b(),c()}Tynt.getUspString=function(){return a.uspString}}},Z=1,H=2,M=0,A=3,O=4,N=5;h.type=0;h.inIframe=function(){return this.type>M};h.inSOIframe=function(){return this.type>=N&&6>=this.type};h.inXOIframe=function(){return this.type>=A&&this.type<=O};h.init=
function(){this.type=f.iframeType();this.inSOIframe()&&(e=f.getTopWin(),g=e.document);e._33Across||(e._33Across={});e._33Across.state||(e._33Across.state={icDone:0,deDone:0,dxDone:0,ivDone:!1});this.protocol="https://";f.init();I.init();G.init();this.isolated=f.isolated();e._33Across.pvTs||(e._33Across.pvTs=Date.now())};L.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},
parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};h.init();var m=g.body,p=g.documentElement,aa=e.eval("/*@cc_on!@*/false"),Q=function(a,b){for(var c="",d=0;d<b;d++)c+=a;return c},D=Q("a",50),C=(Tynt.e||
"")+"ic.tynt.com",R=C+"/b/s",ba=function(a){"complete"==g.readyState?a():Y(e,"load",function(b){setTimeout(function(){"undefined"!=typeof g.readyState||aa||(g.readyState="complete");a()},10)})},w=function(a,b){var c=[],d=function(a,b){var c=h.protocol+a.replace("id="+D,"id="+f.tyntIds());-1<c.indexOf(C+"/b/p?")&&"string"==typeof Tynt.b&&(c+="&b="+Tynt.b);var d=new Image(1,1);b&&(d.onerror=b);d.src=c};w=function(a,b){c.push([a,b])};ba(function(){w=d;for(var a=0;a<c.length;a++)w(c[a][0],c[a][1]);c=
null});w(a,b)},S=function(a){var b=[],c="",d;for(d in a)a.hasOwnProperty(d)&&(b.push(c,d,"=",a[d]),c="&");return b.join("")},U=function(a){for(var b=0,c=100>a.length?a.length:100,d=0;d<c;d++)b+=a.charCodeAt(d);a=Math.floor(3844*Math.random());c=Math.abs(Date.now()-12281184E5);return T(c,7)+T((b+a)%3844,2)},V=function(a){if(62>a)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);var b=Math.floor(a/62);a-=62*b;return 62<=b?V(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):
"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)},T=function(a,b){var c=V(a);return Q("0",b-c.length)+c},ca=f.trim((g.title||e.location.hostname).toString()).replace(new RegExp(e.location.hash,"g"),""),da=function(){if(-1!==g.cookie.indexOf("tracertraffic=")&&(!g.referrer||-1==g.referrer.indexOf(e.location.host))){var a=e.location.hostname.split("."),b,c=2;do b="tracertraffic=0;path=/;domain=."+a.slice(a.length-
c,a.length).join(".")+";expires=Thu, 01 Jan 1970 00:00:00 GMT",g.cookie=b,c++;while(-1==g.cookie.indexOf("tracertraffic=0")&&c<=a.length);-1==g.cookie.indexOf("tracertraffic=0")&&(g.cookie="tracertraffic=0;path=/;expires=Thu, 01 Jan 1970 00:00:00 GMT")}},u=function(){var a=[];return function(b){for(var c=a.length-1;0<=c;c--)if(a[c]==b)return!1;a.unshift(b);3<a.length&&a.pop();return!0}},ea=u(),fa=u(),ga=function(a){var b,c=function(a){e.removeEventListener("blur",c,!1);J(b);return!0};return function(a){b=
a.target||a.srcElement;e.removeEventListener("blur",c,!1);"IMG"==b.nodeName&&"A"!=b.parentNode.nodeName&&(e.addEventListener("blur",c,!1),setTimeout(function(){g.removeEventListener("blur",c,!1)},1E4));return!0}}(),W=function(a){J(a.target||a.srcElement,!0)},v,X=function(a){a=a.target||a.srcElement;v="IMG"==a.nodeName?a:null},K=function(a){var b=function(a){return"number"==typeof a.pageX?{x:a.pageX-(p.scrollLeft?p.scrollLeft:m.scrollLeft),y:a.pageY-(p.scrollTop?p.scrollTop:m.scrollTop)}:{x:a.clientX,
y:a.clientY}},c=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=m.clientWidth||a.y>=m.clientHeight},d=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=p.clientWidth||a.y>=p.clientHeight},e=function(a){return"#document"==a.target.nodeName},f=function(a){a=b(a);return 4>=a.x||4>=a.y||a.x>=p.clientWidth-4||a.y>=p.clientHeight-4},n=function(a){n=navigator.userAgent.match("MSIE")?g.compatMode&&-1!=g.compatMode.indexOf("CSS")?d:c:navigator.userAgent.match("Firefox")?e:f;n(a)};return function(a){v&&n(a)&&(J(v),
v=null);return!0}}();Tynt.ci=function(){var a;return function(b,c){a=c||a;var d=R+["?ci=",b,"&id=",D,"&g=",a,"&r=",encodeURIComponent(g.referrer),"&ts=",Date.now()].join("");w(d)}}();Tynt.st=function(){var a;return function(b,c,d,f){a=d||a;b=[R,"?",encodeURIComponent(b),"=",encodeURIComponent(c),"&id=",D,"&g=",a,"&r=",encodeURIComponent(g.referrer),"&href=",encodeURIComponent(e.location.href),"&ts=",Date.now()];c="";if(f){c=[];d="";for(var h in f)f.hasOwnProperty(h)&&(c.push(d,encodeURIComponent(h),
"=",encodeURIComponent(f[h])),d="&");c="&"+c.join("")}w(b.join("")+c)}}();Tynt.c?u=function(){}:(Tynt.c=!0,Tynt.m=Tynt.m||[],Tynt.n=Tynt.n||[],u=function(){var a=!0,b,c=function(b,c){var d;d=(d=f.trim(c))?d.split(/\s+/i).length:0;var e={id:D,wc:d,c:c,f:a?1:0,t:ca};f.extend(e,b);a=!1;d=e.trace_type;delete e.trace_type;var g=e.g;delete e.g;for(var B=[],t="id wc f w h t c".split(" "),r=0;r<t.length;r++){var p=t[r],m=e[p];m&&B.push([p,encodeURIComponent(m).replace(/\'/g,"%27")]);delete e[p]}for(var q in e)e.hasOwnProperty(q)&&
(t=e[q])&&B.push([q,encodeURIComponent(t).replace(/\'/g,"%27")]);q=[];var r=2048-((h.protocol+C+"/a/t/x#?").length+(3+g.length)+5),p=B.length,x=m=0,y=0,u,v,A,E,F=0;for(q[F]={g:g,tp:null};m<p&&35>q.length;)u=B[m][0],e=B[m][1],A=u.length+2,v=r-A-x,0<v?(t=e.substring(y,y+v),E=t.slice(-2).indexOf("%"),-1<E&&(t=e.substring(y,y+v-2+E),x+=E+2),x+=t.length+A,y+=t.length,q[F][u]=t):x=r,x>=r&&(q[++F]={g:g,p:F},x=0),y>=e.length&&(m++,y=0);q[0].tp=q.length;w(C+"/b/t/"+d+"?"+S(q[0]));for(g=1;g<q.length;g++)w(C+
"/b/x/"+d+"?"+S(q[g]))};e.addEventListener?(navigator.userAgent.match(/Firefox\/2\b/)||m.addEventListener("copy",W,!1),e.addEventListener("mousedown",X,!1),e.addEventListener("dragleave",K,!1),e.addEventListener("dragexit",K,!1),g.addEventListener("contextmenu",ga,!1)):(m.attachEvent("oncopy",W),g.getElementsByTagName("html")[0].attachEvent("ondragleave",K),m.attachEvent("onmousedown",X));da();f.callIc();var d=[15E3,15E3,15E3,15E3];!0===Tynt.TIL?f.callDeb(3,d,!0):f.callDeb(5,d,!0);return function(a,
d){if(!g.getElementById("tyntSh")){var n,k,h;d&&(g.selection&&g.selection.createRange?(k=g.selection.createRange(),h=k.duplicate(),n=k.text):(k=e.getSelection(),h=0<k.rangeCount&&k.getRangeAt(0),n=k.toString()));var m=a.src;if(m&&!n&&fa(m)){k={trace_type:3,g:U(m),w:a.width,h:a.height};for(h=0;h<Tynt.n.length;h++)Tynt.n[h](k,m);c(k,m)}else if(n&&f.trim(n).length&&"TEXTAREA"!=a.nodeName&&"INPUT"!=a.nodeName){m=ea(n);k={trace_type:1};m&&(b=U(n));k.g=b;for(var p=!0,r=0;r<Tynt.m.length;r++)p=p&&Tynt.m[r](k,
n,h,m);m&&p&&c(k,n)}}}});if(!/tracer=test|tracer=no_tracing|disableTracer=/.test(e.location.href)&&!/disableTracer=y/.test(g.cookie))var J=u()}else setTimeout(function(){Tynt.TCL()},50)};Tynt.TCL()}();
